# Todo Application Configuration
name: Todo App
version: 1.0.0
description: A simple Todo application built with the YAML-driven framework

# Server configuration
port: 3000
apiBasePath: /api
production: false

# Database configuration
database:
  type: sqlite
  connection:
    filename: ./data/todo-app.db
    # Use in-memory for testing:
    # memory: true
  synchronize: true # Auto-create tables in development
  pool:
    min: 1
    max: 10

# Authentication configuration
auth:
  provider: jwt
  secret: ${process.env.JWT_SECRET || 'change-me-in-production'}
  tokenExpiry: 24h
  refreshTokenExpiry: 7d
  userEntity: User
  usernameField: email
  passwordField: password
  roleField: role
  # Available roles
  roles:
    - name: admin
      description: Administrator with full access
    - name: user
      description: Regular user with limited access

# Entities configuration
entitiesDir: ./entities

# Logging configuration
logging:
  level: info # debug, info, warn, error
  format: simple # simple, json
  output: console # console, file
  file: ./logs/app.log # Only used when output is file

# Email configuration (for notifications)
email:
  enabled: false
  provider: smtp
  from: noreply@example.com
  smtp:
    host: smtp.example.com
    port: 587
    secure: false
    auth:
      user: ${process.env.SMTP_USER}
      pass: ${process.env.SMTP_PASS}

# UI configuration
ui:
  enabled: true
  pages:
    - name: home
      path: /
      auth: false
      layout: default
      components:
        - type: Hero
          title: Welcome to Todo App
          subtitle: Manage your tasks with ease

    - name: dashboard
      path: /dashboard
      auth: true
      layout: default
      components:
        - type: TodoStats
        - type: TodoList
          title: My Tasks
          defaultView: pending

    - name: todoDetails
      path: /todos/:id
      auth: true
      layout: default
      components:
        - type: TodoDetail

    - name: admin
      path: /admin
      auth: [admin]
      layout: admin
      components:
        - type: UserManagement
        - type: SystemStats

# Migration configuration
migrations:
  dir: ./migrations
  table: migrations
  autoRun: true

# Plugin configuration
plugins:
  - name: Todo Stats
    enabled: true
    options:
      enableCharts: true
      calculateTrends: true

  - name: Task Reminders
    enabled: true
    options:
      checkInterval: 3600 # seconds
      notificationMethods: [email, inApp]

# Custom configuration for business logic
settings:
  maxTodosPerUser: 100
  defaultPriority: 3
  allowedCategories:
    - Work
    - Personal
    - Health
    - Finance
    - Education
    - Other
  priorityLabels:
    1: Very Low
    2: Low
    3: Medium
    4: High
    5: Critical
  autoArchiveCompletedAfterDays: 30

# Development tools
dev:
  enableSwagger: true
  swaggerPath: /api-docs
  cors:
    enabled: true
    origin: "*"
  hotReload: true
